coverage:
  ignore:
    - "src/*/lib*.jl"
    - "src/device"
    - "docs/"
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
    changes: false
comment: false
