# generated by hand ;(

const librocsparse = "librocsparse"

function rocsparse_get_version(handle)
    version = Ref{Cint}()
    ccall((:rocsparse_get_version, "librocsparse"), rocsparse_status_t, (rocsparse_handle, Ptr{Cint}), handle, version)
    return unsafe_load(Base.unsafe_convert(Ptr{Cint}, version))
end

function rocsparse_create_handle()
    handle = Ref{rocsparse_handle}()
    ccall((:rocsparse_create_handle, "librocsparse"), rocsparse_status_t, (Ptr{rocsparse_handle},), handle)
    return handle[]
end

function rocsparse_destroy_handle(handle)
    ccall((:rocsparse_destroy_handle, "librocsparse"), rocsparse_status_t, (rocsparse_handle,), handle)
end