
# Constants

const AMD_QUEUE_ALIGN_BYTES = 64
const AMD_SIGNAL_ALIGN_BYTES = 64
const API_TABLE_MAJOR_VERSION = 0x01
const CORE_API_TABLE_MAJOR_VERSION = 0x01
const AMD_EXT_API_TABLE_MAJOR_VERSION = 0x01
const FINALIZER_API_TABLE_MAJOR_VERSION = 0x01
const IMAGE_API_TABLE_MAJOR_VERSION = 0x01
const AQLPROFILE_API_TABLE_MAJOR_VERSION = 0x01
const API_TABLE_STEP_VERSION = 0x00
const CORE_API_TABLE_STEP_VERSION = 0x00
const AMD_EXT_API_TABLE_STEP_VERSION = 0x00
const FINALIZER_API_TABLE_STEP_VERSION = 0x00
const IMAGE_API_TABLE_STEP_VERSION = 0x00
const AQLPROFILE_API_TABLE_STEP_VERSION = 0x00
const AMD_INTERFACE_VERSION_MAJOR = 1
const AMD_INTERFACE_VERSION_MINOR = 0
const AQLPROFILE_VERSION_MAJOR = 2
const AQLPROFILE_VERSION_MINOR = 0
const AMD_AQLPROFILE_VERSION_MAJOR = 1
#const AQLProfile_Pfn = AQLProfile_1_00_pfn
const VenAMD_loader = 1000


